---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.projectName }}-{{ .Values.envName }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: {{ .Values.projectName }}-{{ .Values.envName }}
spec:
  hard:
    {{- if .Values.config }}
      {{- with .Values.config.quotas }}
      pods: {{ .pods | default "10" }}
      requests.cpu: {{ .cpuRequest | default "2" }}
      requests.memory: {{ .memoryRequest | default "2Gi" }}
      limits.cpu: {{ .cpuLimit | default "8" }}
      limits.memory: {{ .memoryLimit | default "8Gi" }}
      {{- end }}
      {{- else }}
      pods: "10"
      requests.cpu: "2"
      requests.memory: "2Gi"
      limits.cpu: "8"
      limits.memory: "8Gi"
      {{- end }}