kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-operator-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: patch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-cluster-version
  namespace: resource-locker-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  patches:
    - id: patch1
      patchTemplate: |
        spec:
          channel: {{ .Values.channel }}
          desiredUpdate:
            version: {{ .Values.version }}
            force: true
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        name: version
        kind: ClusterVersion