apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: pminkows-cicd
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  rbac:
    defaultPolicy: ''
    policy: |
      g, cluster-admins, role:admin
      g, app-owners, role:admin
    scopes: '[groups]'
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  dex:
    openShiftOAuth: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
---
kind: Secret
apiVersion: v1
metadata:
  name: cluster-api.emarq830.eastus.aroapp.io-592706168
  namespace: pminkows-cicd
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    managed-by: argocd.argoproj.io
data:
  config: >-
    eyJiZWFyZXJUb2tlbiI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJbHBDY1dWc2FWbHhVemxMZDJSM09TMURiaTAyUkdOblowVk1XRkIzYVc1c1R6UTJaMUExUzE4eFdVMGlmUS5leUpwYzNNaU9pSnJkV0psY201bGRHVnpMM05sY25acFkyVmhZMk52ZFc1MElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl1WVcxbGMzQmhZMlVpT2lKcmRXSmxMWE41YzNSbGJTSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWamNtVjBMbTVoYldVaU9pSmhjbWR2WTJRdGJXRnVZV2RsY2kxMGIydGxiaTFxTlhKclpDSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSmhjbWR2WTJRdGJXRnVZV2RsY2lJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExuVnBaQ0k2SWpFd1ltTTBNalF3TFRjNE16VXROR0l3WmkwNU9UWTRMVFU1TjJVeU9XTm1aR1EwTUNJc0luTjFZaUk2SW5ONWMzUmxiVHB6WlhKMmFXTmxZV05qYjNWdWREcHJkV0psTFhONWMzUmxiVHBoY21kdlkyUXRiV0Z1WVdkbGNpSjkuSzJfd0hkeVdkcUV0WktkNGw2R0pIUjd2RndhM2xfVlZVX09SVGdFTGpJNVBOSnMtU3B4aFliakxKMnBxWUduckt0clRuUHAzZlcxQ3pIdjZmdVhxNzZyMWItTmZtbTNWOFhiVUNTQ3FZQmFGRTVSVGJvbzFldlZvaXhDV3MwSWxOd1JSRXVmNG5abFF4NWN5OTlYU3ctUjIwQjJwbDQwQTg4R01oNElqS0dQMXEwWHZqQy1xaGhsMS15YUUwTkV5ZlRMRUY4a0xUcVlRSHI3REJDX2FDUXpqaEhka3dHYUNwdzhQRGd3SHQzaW1RanlQc2RDNlgzMTZMb0pqcXNVbjF2YWg5Z3d4YVJsRVFrLS1BcHh1Q00ydnZ5VC1DLW5ZdE9XSkVaN2UzTzYwa1hpeXBFTy1XajkxWVpJbFNVdkVvV1BFVDk0WngyQWREWkNlUk5ZWHFqbG5mRC1lbWNmS2cxemZhRFE4TGpQSXVtS1ZOZTFsdWx2Mm5ZOVExckVyaTR6TWNydVV4YWY0cU9vVXlVR2IzYTFlREZKUGQyWVJnSE1sTzRfVy0tczY5TjQyN1BqUDQzSTdaQUthSVhSNGFQTUkycE16aEF3Q0ozaWRWVzFFMm1rdXNnWHVMYUpaLVVmLS1CN1h3a005MjhCcGZXeDU3cWsyN2diOGl0enBTWVNqLVZJaS1yMGJ1NHo1elRDSWxXY1Vub1k5RENwdHpHTE5UdTV2bU53aDYzWkoyUUg2OXFBWEphM05URHltSDZjMHNmZEQ5OVdLTGxsZ205ajBtOFNQbThPQ2gydlFMTDhGaGxEYnNkRmx6ZnotbGNoMUhsWDBMTVVmbV9wX2xObk8tQTZqZWtJeVJzZllsd2ZJLWtaYktobEhGQjVnY2lwaUJrNGc5emciLCJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: ZGVmYXVsdC9hcGktZW1hcnE4MzAtZWFzdHVzLWFyb2FwcC1pbzo2NDQzL2t1YmU6YWRtaW4=
  server: aHR0cHM6Ly9hcGkuZW1hcnE4MzAuZWFzdHVzLmFyb2FwcC5pbzo2NDQz
type: Opaque