apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-config
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/piomin/openshift-cluster-config.git
        revision: HEAD
        files:
          - path: applicationset/projects/**/**/values.yaml
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-{{ index .path.segments 3 }}-ns'
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{ default (index .path.segments 3) .cluster.name }}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: 'true'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
    spec:
      destination:
        name: '{{ default (index .path.segments 3) .cluster.name }}'
      project: global
      sources:
        - path: applicationset/chart2
          repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/applicationset/projects/{{ index .path.segments 2 }}/{{ index .path.segments 3 }}/values.yaml
            parameters:
              - name: projectName
                value: '{{ index .path.segments 2 }}'
              - name: envName
                value: '{{ index .path.segments 3 }}'
        - repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
          targetRevision: HEAD
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true