apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}
    baseDomain: {{ .Values.domain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        {{- if eq .Values.provider "Google" }}
        gcp:
          type: {{ .Values.workerType }}
        {{- end }}
        {{- if eq .Values.provider "Amazon" }}
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: {{ .Values.workerType }}
        {{- end }}
    compute:
      - hyperthreading: Enabled
        name: 'worker'
        replicas: {{ .Values.workerReplicas }}
        {{- if eq .Values.provider "Google" }}
        gcp:
          type: {{ .Values.workerType }}
        {{- end }}
        {{- if eq .Values.provider "Amazon" }}
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: {{ .Values.workerType }}
        {{- end }}
    networking:
      networkType: OpenShiftSDN
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
    platform:
      {{- if eq .Values.provider "Google" }}
      gcp:
        projectID: {{ .Values.project }}
        region: {{ .Values.region }}
      {{- end }}
      {{- if eq .Values.provider "Amazon" }}
      aws:
        region: {{ .Values.region }}
      {{- end }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKAlQfTe6SuI8/SaWOTUg9EwNcvs+1148EdBWcSfPz44 pminkows@pminkows-mac